[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://portfolio-site.prismic.io/api/v2 https://portfolio-site.cdn.prismic.io/api/v2/documents/search https://storage.googleapis.com https://www.google-analytics.com https://polyfill.io https://cdn.logrocket.io https://r.logrocket.io https://d33wubrfki0l68.cloudfront.net; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://polyfill.io https://cdn.logrocket.io https://ajax.cloudflare.com https://d33wubrfki0l68.cloudfront.net https://sentry.io https://www.google-analytics.com; img-src 'self' data: https://portfolio-site.cdn.prismic.io https://storage.googleapis.com https://www.google-analytics.com https://stats.g.doubleclick.net https://www.google.co.za/ads https://www.google.com/ads; style-src 'self' 'unsafe-inline'; connect-src https://asjas.co.za https://asjas.sfo2.cdn.digitaloceanspaces.com https://r.logrocket.io https://cdn.logrocket.io https://d33wubrfki0l68.cloudfront.net https://www.google-analytics.com; font-src https://asjas.sfo2.cdn.digitaloceanspaces.com; form-action 'none'; worker-src 'self' blob: data:; report-uri https://asjas.report-uri.com/r/d/csp/enforce; report-to default"
    X-Content-Security-Policy = "default-src 'self' https://portfolio-site.prismic.io/api/v2 https://portfolio-site.cdn.prismic.io/api/v2/documents/search https://storage.googleapis.com https://www.google-analytics.com https://polyfill.io https://cdn.logrocket.io https://r.logrocket.io https://d33wubrfki0l68.cloudfront.net; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://polyfill.io https://cdn.logrocket.io https://ajax.cloudflare.com https://d33wubrfki0l68.cloudfront.net https://sentry.io https://www.google-analytics.com; img-src 'self' data: https://portfolio-site.cdn.prismic.io https://storage.googleapis.com https://www.google-analytics.com https://stats.g.doubleclick.net https://www.google.co.za/ads https://www.google.com/ads; style-src 'self' 'unsafe-inline'; connect-src https://asjas.co.za https://asjas.sfo2.cdn.digitaloceanspaces.com https://r.logrocket.io https://cdn.logrocket.io https://d33wubrfki0l68.cloudfront.net https://www.google-analytics.com; font-src https://asjas.sfo2.cdn.digitaloceanspaces.com; form-action 'none'; worker-src 'self' blob: data:; report-uri https://asjas.report-uri.com/r/d/csp/enforce; report-to default"
    Expect-CT = "max-age=604800, report-uri https://asjas.report-uri.com/r/d/ct/enforce; report-to default"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubdomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Feature-Policy = "geolocation 'none'; camera 'none'; payment 'none'; usb 'none'; midi 'none'"
    Report-To = "{'group':'default','max_age':31536000,'endpoints':[{'url':'https://asjas.report-uri.com/a/d/g'}],'include_subdomains':true}"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate;"

[[headers]]
  for = "/*.js|*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable;"

[[headers]]
  for = "sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store;"

[[headers]]
  for = "/*.jpg|*.jpeg|*.webp|*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable;"
