[[headers]]
  for = "/*"
  [headers.values]
    Expect-CT = "max-age=604800, report-uri https://asjas.report-uri.com/r/d/ct/enforce; report-to default"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubdomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Feature-Policy = "geolocation 'none'; camera 'none'; payment 'none'; usb 'none'; midi 'none'"
    Report-To = "{'group':'default','max_age':31536000,'endpoints':[{'url':'https://asjas.report-uri.com/a/d/g'}],'include_subdomains':true}"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate;"

[[headers]]
  for = "/*.js|*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable;"

[[headers]]
  for = "sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store;"

[[headers]]
  for = "/*.jpg|*.jpeg|*.webp|*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable;"
