account_id = "d34e365e96c3cd636081f05b0a6b031a"
name = "personal-website"
type = "webpack"
route = "https://asjas.xyz/*"
workers_dev = false
zone_id = "34bf06b11a24aee26d1c99056fe3fdf9"

[site]
bucket = "./public/"
entry-point = "workers-site"

[email]
bucket = "./functions/"
entry-point = "functions"
