name: Gatsby-CF-Deploy

on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    name: Test accessibility, build Gatsby site and deploy to Cloudflare Workers
    steps:
      - name: Checkout Git Source
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.16.1'

      - name: Install npm packages
        run: yarn

      - name: Build Gatsby Site
        run: yarn build

      - name: Cypress Chrome
        run: yarn test:e2e:chrome:ci

      - name: Cypress Firefox
        run: yarn test:e2e:firefox:ci

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
